# Generated by Django 5.2.4 on 2025-07-27 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option_one',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_two',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='option_three',
            new_name='option3',
        ),
        migrations.AddField(
            model_name='poll',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
